a = input("Digite algo: ")
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É um alfabeto?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Está em maisculas?', a.isupper())
print('Está em minusculas?', a.islower())
print('Está capitaizada?', a.istitle())
